# permissions for end users to view configmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sample-controller
    app.kubernetes.io/managed-by: kustomize
  name: configmap-viewer-role
rules:
- apiGroups:
  - api.operatortest.io
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.operatortest.io
  resources:
  - configmaps/status
  verbs:
  - get
